from flask import Flask, request, jsonify
import requests
import os

app = Flask(__name__)

# ==========================
# API KEYS
# ==========================
GROQ_KEY = os.getenv("GROQ_KEY")
GEMINI_KEY = os.getenv("GEMINI_KEY")
DEEPSEEK_KEY = os.getenv("DEEPSEEK_KEY")
OPENAI_KEY = os.getenv("OPENAI_KEY")
ANTHROPIC_KEY = os.getenv("ANTHROPIC_KEY")

print("===== PROJECT ATLAS =====")
print("Groq      :", "Loaded" if GROQ_KEY else "Missing")
print("Gemini    :", "Loaded" if GEMINI_KEY else "Missing")
print("DeepSeek  :", "Loaded" if DEEPSEEK_KEY else "Missing")
print("OpenAI    :", "Loaded" if OPENAI_KEY else "Missing")


# ==========================
# HOME PAGE
# ==========================
@app.route("/")
def home():
    return "Project Atlas is running!"


# ==========================
# GROQ
# ==========================
def ask_groq(question):
    url = "https://api.groq.com/openai/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {GROQ_KEY}",
        "Content-Type": "application/json"
    }

    body = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }

    response = requests.post(url, headers=headers, json=body)

    if response.status_code != 200:
        return {"error": response.text}

    result = response.json()
    return {"answer": result["choices"][0]["message"]["content"]}


# ==========================
# GEMINI (UPDATED)
# ==========================
def ask_gemini(question):
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"

    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": GEMINI_KEY  # Passed via header for safety
    }

    body = {
        "contents": [
            {
                "parts": [
                    {
                        "text": question
                    }
                ]
            }
        ]
    }

    response = requests.post(url, headers=headers, json=body)

    if response.status_code != 200:
        return {"error": response.text}

    result = response.json()

    # Safe extraction to prevent crashes on blocked or empty responses
    try:
        candidate = result.get("candidates", [])[0]
        parts = candidate.get("content", {}).get("parts", [])
        if parts:
            return {"answer": parts[0].get("text", "")}
        return {"error": "No text content generated by the model."}
    except (IndexError, KeyError, TypeError) as e:
        return {"error": f"Failed to parse Gemini response: {str(e)}"}


# ==========================
# CHATGPT
# ==========================
def ask_openai(question):
    url = "https://api.openai.com/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {OPENAI_KEY}",
        "Content-Type": "application/json"
    }

    body = {
        "model": "gpt-4.1-mini",
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }

    response = requests.post(url, headers=headers, json=body)

    if response.status_code != 200:
        return {"error": response.text}

    result = response.json()
    return {"answer": result["choices"][0]["message"]["content"]}

def ask_claude(question):

    url = "https://api.anthropic.com/v1/messages"

    headers = {
        "x-api-key": ANTHROPIC_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
    }

    body = {
        "model": "claude-3-5-haiku-latest",
        "max_tokens": 1024,
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }

    response = requests.post(url, headers=headers, json=body)

    if response.status_code != 200:
        return {"error": response.text}

    result = response.json()

    return {
        "answer": result["content"][0]["text"]
    }
  
# ==========================
# DEEPSEEK
# ==========================
def ask_deepseek(question):
    url = "https://api.deepseek.com/chat/completions"

    headers = {
        "Authorization": f"Bearer {DEEPSEEK_KEY}",
        "Content-Type": "application/json"
    }

    body = {
        "model": "deepseek-chat",
        "messages": [
            {
                "role": "user",
                "content": question
            }
        ]
    }

    response = requests.post(url, headers=headers, json=body)

    if response.status_code != 200:
        return {"error": response.text}

    result = response.json()
    return {"answer": result["choices"][0]["message"]["content"]}


# ==========================
# ASK ROUTE
# ==========================
@app.route("/ask", methods=["POST"])
def ask():
    data = request.get_json(force=True)

    if not data:
        return jsonify({"error": "No JSON received"}), 400

    question = data.get("question")
    model = data.get("model", "groq").lower()

    if model == "groq":
        result = ask_groq(question)

    elif model == "gemini":
        result = ask_gemini(question)

    elif model == "chatgpt":
        result = ask_openai(question)

    elif model == "deepseek":
        result = ask_deepseek(question)

    elif model == "claude":
        result = ask_claude(question)
       
    else:
        result = ask_groq(question)

    return jsonify(result)

@app.route("/compare", methods=["POST"])
def compare():
    data = request.get_json()
    question = data.get("question", "")

    try:
        chatgpt = ask_openai(question)
    except Exception as e:
        chatgpt = {"error": str(e)}

    try:
        gemini = ask_gemini(question)
    except Exception as e:
        gemini = {"error": str(e)}

    try:
        groq = ask_groq(question)
    except Exception as e:
        groq = {"error": str(e)}

    try:
        claude = ask_claude(question)
    except Exception as e:
        claude = {"error": str(e)}

    try:
        deepseek = ask_deepseek(question)
    except Exception as e:
        deepseek = {"error": str(e)}

    final_answer = f"""
PROJECT ATLAS
AI COMPARISON

Question:
{question}

ChatGPT
{get_text(chatgpt)}

Gemini
{get_text(gemini)}

Groq
{get_text(groq)}

Claude
{get_text(claude)}

DeepSeek
{get_text(deepseek)}
"""
    return final_answer

def get_text(response):
    if isinstance(response, dict):
        if "answer" in response:
            text = response["answer"]
        elif "error" in response:
            text = "❌ " + str(response["error"])
        else:
            text = str(response)
    else:
        text = str(response)

    text = text.replace("###", "")
    text = text.replace("##", "")
    text = text.replace("**", "")
    text = text.replace("`", "")
    text = text.replace("* ", "• ")

    return text.strip()

    final_answer = f"""
══════════════════════════════════════
            PROJECT ATLAS
══════════════════════════════════════

 QUESTION
{question}

══════════════════════════════════════

 ChatGPT
──────────────────────────────────────
{get_text(chatgpt)}

══════════════════════════════════════

 Gemini
──────────────────────────────────────
{get_text(gemini)}

══════════════════════════════════════

 Groq
──────────────────────────────────────
{get_text(groq)}

══════════════════════════════════════

 Claude
──────────────────────────────────────
{get_text(claude)}

══════════════════════════════════════

 DeepSeek
──────────────────────────────────────
{get_text(deepseek)}

══════════════════════════════════════
Generated by Project Atlas
"""
    return final_answer

# ==========================
# TEST ROUTE
# ==========================
@app.route("/test", methods=["POST"])
def test():
    return request.get_data(as_text=True)


# ==========================
# MAIN
# ==========================
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
